version: '3.8'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    tty: true
    volumes:
      - .:/code
    networks:
      - laravel_network

  web:
    container_name: web
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    depends_on:
      - app
    volumes:
      - ./public:/code/public
    ports:
      - '${DOCKER_FORWARD_PORT:-80}:80'
    environment:
      - TZ=${APP_TIMEZONE}
    links:
      - app
    networks:
      - laravel_network

  minio:
    image: minio/minio:latest
    container_name: minio_s3
    volumes:
      - minio-store:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - laravel_network
    command: server /data --console-address ":9001"

networks:
  laravel_network:
    external: true
