version: '3'

services:
  php:
    restart: unless-stopped
    build:
      context: .
      dockerfile: build_setup/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./source_code:/app/code
      - /app/code/vendor
      - /app/code/node_modules
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - "3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    volumes:
      - ../sd_mysqldata:/var/lib/mysql

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 3002:8080
