version: '3'

services:
  ### python django + nginx
  django:
    restart: unless-stopped
    build:
      context: .
      dockerfile: build_setup/Dockerfile
    volumes:
      - ./src/static_cdn/:/app/code/static_cdn
    env_file: ./scripts/django_env.conf
    ports:
      - "8000"
    depends_on:
      - db
  db:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - "3306"
    environment:
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ../st_mysqldata:/var/lib/mysql

  redis:
    image: redis:6.0-rc-buster
    restart: unless-stopped
    ports:
      - "6379"

  celery:
    restart: unless-stopped
    build: .
    volumes:
      - ./src/:/app/code
    env_file: ./scripts/django_env.conf
    command: celery -A tetviet worker -B -l info
    depends_on:
      - redis
      - db
