version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      - "MYSQL_USER=root"
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - link
  adminer:
    image: adminer:4.7.6
    restart: always
    ports:
      - 3002:8080
    networks:
      - link

networks:
  link:
    driver: bridge
